/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as HobbyRouteImport } from './routes/hobby'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as LancamentosRouteImport } from './routes/lancamentos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const HobbyRoute = HobbyRouteImport.update({
  id: '/hobby',
  path: '/hobby',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contas': typeof ContasRoute
  '/hobby': typeof HobbyRoute
  '/investimentos': typeof InvestimentosRoute
  '/lancamentos': typeof LancamentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contas': typeof ContasRoute
  '/hobby': typeof HobbyRoute
  '/investimentos': typeof InvestimentosRoute
  '/lancamentos': typeof LancamentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contas': typeof ContasRoute
  '/hobby': typeof HobbyRoute
  '/investimentos': typeof InvestimentosRoute
  '/lancamentos': typeof LancamentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contas' | '/hobby' | '/investimentos' | '/lancamentos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contas' | '/hobby' | '/investimentos' | '/lancamentos'
  id:
    '__root__' | '/' | '/contas' | '/hobby' | '/investimentos' | '/lancamentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContasRoute: typeof ContasRoute
  HobbyRoute: typeof HobbyRoute
  InvestimentosRoute: typeof InvestimentosRoute
  LancamentosRoute: typeof LancamentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobby': {
      id: '/hobby'
      path: '/hobby'
      fullPath: '/hobby'
      preLoaderRoute: typeof HobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContasRoute: ContasRoute,
  HobbyRoute: HobbyRoute,
  InvestimentosRoute: InvestimentosRoute,
  LancamentosRoute: LancamentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
